# Generated by Django 3.2.18 on 2023-03-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0003_clinic_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djapp.clinic'),
        ),
    ]
