# Generated by Django 3.2.18 on 2023-03-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0004_auto_20230324_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor',
            new_name='clinicname',
        ),
    ]
