# Generated by Django 3.2.18 on 2023-03-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0005_rename_doctor_doctor_clinicname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinicname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djapp.clinic'),
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('phonenumber', models.CharField(max_length=30, null=True)),
                ('clinicname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djapp.clinic')),
            ],
        ),
    ]
