# Generated by Django 3.2.18 on 2023-03-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0006_auto_20230324_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='doctor2',
            field=models.ManyToManyField(to='djapp.Doctor'),
        ),
    ]
