# Generated by Django 3.2.18 on 2023-03-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0008_auto_20230324_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
