# Generated by Django 3.2.18 on 2023-03-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0009_auto_20230324_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinicname',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
