# Generated by Django 3.2.18 on 2023-03-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0011_appointment_clinic_customer_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinicstatus',
            field=models.ForeignKey(limit_choices_to={'state': 'open'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='djapp.clinic'),
        ),
    ]
