# Generated by Django 3.2.18 on 2023-03-24 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0012_appointment_clinicstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='clinicstatus',
        ),
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(limit_choices_to={'state': 'open'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='djapp.clinic'),
        ),
    ]
