# Generated by Django 3.2.18 on 2023-03-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0014_auto_20230325_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='clinic',
        ),
    ]
