# Generated by Django 3.2.18 on 2023-03-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0016_auto_20230330_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='region',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='state',
            field=models.CharField(choices=[('open', 'open'), ('close', 'close')], default='close', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
