# Generated by Django 3.2.18 on 2023-03-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0017_auto_20230330_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
