# Generated by Django 3.2.18 on 2023-03-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0018_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinicname',
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='djapp.clinic'),
        ),
    ]
