# Generated by Django 3.2.18 on 2023-03-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0024_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='fullname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
