# Generated by Django 3.2.18 on 2023-03-31 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0026_alter_customer_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fullname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djapp.customer'),
        ),
    ]
