# Generated by Django 3.2.18 on 2023-03-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0027_auto_20230331_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(choices=[('onduty', 'onduty'), ('offduty', 'offduty')], default='offduty', max_length=10),
        ),
    ]
