# Generated by Django 3.2.18 on 2023-03-31 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0028_doctor_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'state': 'onduty'}, on_delete=django.db.models.deletion.CASCADE, to='djapp.doctor'),
        ),
    ]
