# Generated by Django 3.2.18 on 2023-04-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0030_alter_appointment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
