# Generated by Django 3.2.18 on 2023-04-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0032_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
