# Generated by Django 3.2.18 on 2023-04-01 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djapp', '0034_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='djapp.clinic'),
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_superadmin', to='djapp.clinic')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='superadmin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_clinic', to='djapp.superadmin'),
        ),
    ]
