# Generated by Django 3.2.18 on 2023-04-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0036_alter_clinic_superadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'permissions': [('can_manage_clinic', 'Can manage clinic'), ('can_manage_customer', 'Can manage customer'), ('can_manage_doctor', 'Can manage doctor'), ('can_manage_appointment', 'Can manage appointment')]},
        ),
        migrations.AlterModelOptions(
            name='superadmin',
            options={'permissions': [('can_manage_clinic', 'Can manage clinic'), ('can_manage_admin', 'Can manage admin'), ('can_manage_doctor', 'Can manage doctor')]},
        ),
    ]
