# Generated by Django 3.2.18 on 2023-04-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0039_auto_20230402_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superadmin',
            options={'permissions': [('can_manage_clinic', 'Can manage clinic'), ('can_manage_admin', 'Can manage admin'), ('can_manage_doctor', 'Can manage doctor')]},
        ),
    ]
