# Generated by Django 3.2.18 on 2023-04-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0040_alter_superadmin_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
