# Generated by Django 3.2.18 on 2023-04-02 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0043_alter_superadmin_clinic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superadmin',
            options={'permissions': [('can_manage_clinic', 'Can manage clinic'), ('can_manage_admin', 'Can manage admin'), ('can_manage_doctor', 'Can manage doctor'), ('can_manage_customer', 'Can manage customer'), ('can_manage_appointment', 'Can manage appointment')]},
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_superadmin', to='djapp.clinic'),
        ),
    ]
