# Generated by Django 3.2.18 on 2023-04-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0044_auto_20230402_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
    ]
