# Generated by Django 3.2.18 on 2023-05-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0052_customer_login_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='login_status',
        ),
    ]
