# Generated by Django 3.2.18 on 2023-05-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0053_remove_customer_login_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='login_status',
            field=models.BooleanField(default=False),
        ),
    ]
