# Generated by Django 3.2.18 on 2023-05-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0055_chatlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='intent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
