# Generated by Django 3.2.18 on 2023-05-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0056_auto_20230522_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='response',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='user',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='sender',
            field=models.TextField(null=True),
        ),
    ]
